### ISSUE TITLE
my end game saves

### ISSUE THREAD

**Issue by engagexes** [MugenAttack/GB3SaveEditor#1]
hi MugenAttack, really interesting project you have here, i already tested it and worked

here my save i spend a lot of time in this save, and also have optimal build (for me) for Massive AoE damage nuke , almost unkillable unflinch unbreakable melee build, and deadly sniper build do like 2 milion damage per hit, you didnt ask for this but i hope this will be helpful in someway.

its require DLC1-6 though, i dunno how to remove DLC requitment from my saves
https://mir.cr/1KWHRADO

Also that saves actually from my ps4 and its work on my vita, so this save editor may actually support decrypted ps4 saves too ( using SaveWizard to decrypt them if your ps4 is OFW)

**Comment by MugenAttack** [comment]
oh thanks for the ps4 information.    i will update the Readme to include the information.
the save won't be much help cause i need to do specific test on stuff and compare difference in save.

**Comment by engagexes** [comment]
I see, im just too excited when my favorite game got save editor so i  can put op unintended abilities on my gunpla,good luck with developing the editor
